### PR TITLE
Issue/16 UI

### LINKED ISSUE #16: Create website frontend
Github releases are great, but they're a bit intimidating and unintuitive for those who don't know code. Make a frontend (probably via github pages) on which to host the links. This should include:

- [ ] *some* method of searching or filtering the calendars so that the user doesn't have to scroll through 300+ calendars
- [ ] Preferably the links should be clickable, and result in the user being subscribed to the correct calendar
- [ ] A more user-friendly description of the different calendars, explaining which human-readable suburbs are included in each area

### PR DESCRIPTION
**Pull request by Ruandv**
This will solve the WebUi Request closes #16

### CODE REVIEW

**Comment by Ruandv** [comment]
@beyarkay here is a PR yet ;-) . I don't expect you to accept it. I just want to create the PR so that you can hopefully also have access to the branch.

**Comment by beyarkay** [comment]
Okay no worries! I've got access to your branch so it's all good 👍

**Comment by Ruandv** [comment]
Should this UI rather be hosted in its own repo and then it can also be hosted on github pages instead of polluting this calendar generating code?

**Comment by beyarkay** [comment]
Hey, yeah I think separating the UI from the content is a good idea. Do you want to host the UI repo under your own username?

Long term I'll probably end up splitting the loadshedding-event generating code from the calendar publishing code, but that's not going to happen just yet.

**Comment by Ruandv** [comment]
Sure I don't mind having it there for now.

**Pull request closed without merging**
