### PR TITLE
Updated CoCT load shedding times from Twitter

### PR DESCRIPTION
**Pull request by shaunkleyn**
https://twitter.com/CityofCT/status/1583070920864067584

### CODE REVIEW

**Comment by beyarkay** [comment]
LGTM, I'm busy trying to get those builds passing though.

**Comment by beyarkay** [comment]
Thanks again @shaunkleyn, I _think_ 17b5e0f0fda9e0d81d5d6112fb131e4179f9b0e7 should mean that your future contributions should pass the builds (although they might not get the fully featured PR comments just yet). If you've got a sec, would you mind making a dummy PR to change `manually_specified.yaml`? It can literally be adding a newline somewhere (and I won't accept the PR), I just want to confirm that in the future your PRs and others won't result in a failed build for silly reasons.

**Comment by shaunkleyn** [comment]
@beyarkay No problem.  I'll create a dummy PR then we can test the change.

**Comment by beyarkay** [comment]
@all-contributors please add @shaunkleyn to the list of contributors for maintenance

**Comment by beyarkay** [comment]
Okay for real this time, @all-contributors please add @shaunkleyn to the list of contributors for maintenance ❤️

**Pull request merged**
