### PR TITLE
update city power schedules to 2023-11 rev 4

### PR DESCRIPTION
**Pull request by declan-fitzpatrick**
City Power has published a new revision that goes live on [Wednesday 22nd](https://twitter.com/CityPowerJhb/status/1726979497692672032).

Spot checks seem to be passing

### CODE REVIEW

**Comment by beyarkay** [comment]
Thanks! Looking through the commit now.

> City Power has revised the loadshedding schedule that has been a source of public outcry 
in recent weeks^HN

I was totally oblivious that the new schedule was not getting much love. Was it really bad?

**Comment by beyarkay** [comment]
Everything looks good to me. Do you know when these updated schedules go into effect? I couldn't see anything on the city power website and the tweet just said "the new schedule which will be published on Wednesday".

**Comment by declan-fitzpatrick** [comment]
New schedule is live today, cross referencing the .pdf and City Power website.

Main issue is that they have ended up making blocks of 2 hours on, 2 hours off for stages 1-4. And this caused the 'outcry'. Unfortunately it seems this new change has not fixed it completely. 

For example, today's stage 4 has blocks 6, 8, 13, and 15 are off from `04:00-06:30`, `12:00-14:30`, `16:00-18:30`, and `20:00-22:30`. However, it does seem to be more normal (2hrs morning, afternoon and evening) for the rest of the week. Likely another schedule update before the end of the year.

**Comment by c4talyst** [comment]
Takes effect midnight tonight -> 23/11/2023 at 00:00

**Comment by declan-fitzpatrick** [comment]
I'd trust the other guy who made a loadshedding tool over me... ^

Would also explain why schedules look more 'normal' for the rest of the week.

**Comment by beyarkay** [comment]
Okay cool, looks like I jumped the gun a bit with merging but everything's in order now. I'm looking at a better schedule management system which would automatically migrate from old schedules to new ones but that'll likely only come online in the new year.

**Pull request merged**
