### PR TITLE
update city power schedules to 25/12/23

### PR DESCRIPTION
**Pull request by declan-fitzpatrick**
City Power changed blocks and the schedules, that were published on [Christmas Day](https://www.citypower.co.za/customers/Load%20Shedding%20Related%20Documents/CUSTOMER%20NOTICE_LOADSHEDDING%20SCHEDULE%20CHANGES.pdf) 

* added a new file `src/parse_city_power_xlsx.py` as they swapped from .pdf to .xlsx for this update. Contents borrow heavily from `src/parse_eskom_excel.py` with minor tweaks. 
* City Power now has 18 Areas, instead of 16. Area 18 only has "Customer" in it.
* updated `area_metadata.yaml`, and ran yamllint. 

Quick spot checks match up with their [block searching tool in the .xlsx](https://www.citypower.co.za/customers/Load%20Shedding%20Related%20Documents/Load%20Shedding%20Schedule%20Vers%206%20Block%20Areas%20Rev%200.xlsx).

### CODE REVIEW

**Comment by declan-fitzpatrick** [comment]
Will fix #513 #512 #510 #509

**Comment by beyarkay** [comment]
The build's failing because the python script has the date fomatted HH:MM:SS but the rust script is expecting HH:MM, I'm busy fixing the python script now...

**Comment by beyarkay** [comment]
Should be fixed by [8e2f1b5](https://github.com/beyarkay/eskom-calendar/commit/8e2f1b5e55725eb32dd8225e0d473c8f1e20f656)

**Comment by beyarkay** [comment]
Yeah it's all fixed. Thanks for the PR!

**Pull request merged**
