### PR TITLE
Added load shedding schedule from Twitter

### PR DESCRIPTION
**Pull request by shaunkleyn**
https://twitter.com/eskom_sa/status/1583027654034305024

### CODE REVIEW

**Comment by beyarkay** [comment]
Thanks! The build tests are gonna run and if all looks good I'll merge the changes

**Comment by shaunkleyn** [comment]
You are most welcome.  Thanks for this awesome project.

**Comment by beyarkay** [comment]
Not sure why the build failed, trying it again

**Comment by beyarkay** [comment]
Looking into the issue now, I haven't seen this but before

**Comment by beyarkay** [comment]
Ahh I see the problem I think. Going to rebase and merge into main as it's not a problem with your change, but rather my config.

**Comment by shaunkleyn** [comment]
Thank you.  :) I was a bit worried that one of my changes maybe caused it to fail so double checked everything and couldn't spot anything.

**Comment by beyarkay** [comment]
Thanks for helping @shaunkleyn ! really appreciate it. I'm going to watch the GH action [here](https://github.com/beyarkay/eskom-calendar/actions/runs/3288899759/jobs/5419792814) since sometimes it can fail due to network errors and needs a retry.

Can I ask how you found out about the project, and what your experience was of making the PR? I want to get the experience as smooth as possible for new contributors.

**Comment by shaunkleyn** [comment]
You're most welcome.  You started a project we can all benefit from so it's just fair to help out if and when possible.  

I searched GitHub a couple of months ago hoping to find and API that I can use to retrieve load shedding schedules but couldn't find any.  A couple of days ago I was actually just searching for any helpful calendars that I can subscribe to and then came across your project.  I now eventually have a source that I can use to set up stuff on my side based on load shedding schedules; the main one being switching off my Plex server just before the power goes out to prevent disk damage or data loss.

I work with TFS daily but not very comfortable with GitHub yet so I was a little concerned that I might mess something up.  Luckily not :).  The only thing that threw me off a bit was to fork the project first - I followed your steps on how to submit a change but it didn't mention forking the project.  That's the only reason why it threw me off a bit.  Other than that it was quite easy and straight forward.

**Pull request merged**
